# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3387ce9a17d0fb9742eb5de6c69d33b5cea382a0195095ff46f507f9c496cd2a493da377df8ec5c39beb22196d617ca055ca3bd5b479748d961476eea39dacee

test:
  secret_key_base: 389667a3a5a2fd1ac55298904bfb2bfb95f49673724969d130c8a33425ff67a9caabfa97e2cc09203ab7787748900bbbdacf2d8d5b2b4cdd024de358bb61661b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
